CREATE TABLE STUD(NO INT,NAME VARCHAR(20),MARKS INT);
INSERT INTO STUD VALUES(1,'NANDANA',40);
SELECT * FROM STUD;
INSERT INTO STUD VALUES(2,'SRADHA',21);
INSERT INTO STUD VALUES(3,'ASQTHI',35);
SELECT * FROM STUD;

SET SERVEROUTPUT ON;

DECLARE
 avg_marks INT;
 cdate DATE;
 cmonth VARCHAR(20);
 cday VARCHAR(20);
BEGIN
 SELECT AVG(MARKS) INTO avg_marks FROM STUD;
 DBMS_OUTPUT.PUT_LINE('AVERAGE MARKS'||avg_marks);
 IF avg_marks<40 THEN
  DBMS_OUTPUT.PUT_LINE('low');
 ELSE
  DBMS_OUTPUT.PUT_LINE('good');
 END if;
 cdate := SYSDATE;
 DBMS_OUTPUT.PUT_LINE('Current dat'||cdate);
 cmonth := TO_CHAR(cdate,'MONTH');
 DBMS_OUTPUT.PUT_LINE('MONTH'||cmonth);
 cday := TO_CHAR(cdate,'DAY');
 DBMS_OUTPUT.PUT_LINE('DAY'||cday);
END;
/
