CREATE TABLE ROOM(ROOMNO NUMBER primary key,CHARGE NUMBER);
CREATE TABLE GUEST(NAME varchar(20) PRIMARY KEY,ADDRESS VARCHAR(20),ROOMNO NUMBER,CHECKIN DATE,CHECKOUT DATE,foreign KEY(ROOMNO)references ROOM(ROOMNO));
CREATE TABLE BILL(NAME VARCHAR(20),AMOUNT NUMBER,foreign key(NAME)references GUEST(NAME));
CREATE TABLE HISTORY(NAME VARCHAR(20),CHECKOUT DATE,foreign key(NAME)references GUEST(NAME));
INSERT INTO ROOM VALUES(1,800);
INSERT INTO ROOM VALUES(2,1800);
INSERT INTO ROOM VALUES(3,1000);
INSERT INTO ROOM VALUES(4,1500);
select * FROM ROOM;
INSERT INTO GUEST VALUES('NANDANA','KOYILI HOUSE',1,'11-JAN-2024','13-JAN-2024');
INSERT INTO GUEST VALUES('ASWATHI','NUT HOUSE',3,'11-FEB-2024','15-FEB-2024');
INSERT INTO GUEST VALUES('SRADHA','KOZHI HOUSE',2,'01-APR-2024','05-APR-2024');
INSERT INTO GUEST VALUES('ANIL','HS HOUSE',4,'11-NOV-2024','15-NOV-2024');
INSERT INTO GUEST VALUES('SUKU','NW HOUSE',3,'01-NOV-2024','11-NOV-2024');

select * FROM GUEST;


CREATE OR REPLACE PROCEDURE GENBILL(CNAME VARCHAR2,RN NUMBER,CHECKIN DATE,CHECKOUUT DATE) AS 
TOT NUMBER;
CAMOUNT NUMBER;
CHARGEE NUMBER;
DUR NUMBER;
BEGIN
 SELECT CHARGE INTO CHARGEE FROM ROOM WHERE ROOMNO=RN;
 DUR:=CHECKOUUT-CHECKIN;
 TOT:=CHARGEE*DUR;
 INSERT INTO BILL(NAME,AMOUNT) VALUES(CNAME,TOT);
 INSERT INTO HISTORY(NAME,CHECKOUT) VALUES(CNAME,CHECKOUUT);
END GENBILL;
/
SHOW ERRORS;

SET SERVEROUTPUT ON;
ACCEPT CNMAE VARCHAR(20) PROMPT'ENTER NAME';
DECLARE
 RN NUMBER;
 CIN DATE;
 COUT DATE;
 CNAMEE VARCHAR(20);
 REVENUE NUMBER;
 CDATE DATE;
 CMONTH VARCHAR(20);
 UNI NUMBER;
 
BEGIN
  SELECT NAME,ROOMNO,CHECKIN,CHECKOUT INTO CNAMEE,RN,CIN,COUT FROM GUEST WHERE NAME='&CNAME';
  GENBILL(CNAMEE,RN,CIN,COUT);
  SELECT SUM(AMOUNT) INTO REVENUE FROM BILL;
  DBMS_OUTPUT.PUT_LINE('TOTAL REVENUE IS ' ||REVENUE);
  CDATE:=SYSDATE;
  CMONTH:=TO_CHAR(CDATE,'MONTH');
  SELECT DISTINCT COUNT(NAME) INTO UNI FROM GUEST WHERE TO_CHAR(CHECKOUT,'MONTH')=CMONTH  ;
  DBMS_OUTPUT.PUT_LINE('COUNT OF UNIQUE CUSTOMERS IS ' ||UNI);
EXCEPTION
   WHEN NO_DATA_FOUND THEN
      DBMS_OUTPUT.PUT_LINE('No data found for the given input.');
   WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('An error occurred: ' || SQLERRM);
  
END;
/
SELECT * FROM BILL;
SELECT * FROM HISTORY;
SELECT * FROM GUEST G,ROOM B WHERE G.ROOMNO=B.ROOMNO AND B.CHARGE>=1500;
SELECT ROOMNO FROM ROOM  WHERE CHARGE>(SELECT AVG(AMOUNT)FROM BILL);
SELECT R.ROOMNO FROM ROOM R INNER JOIN GUEST G ON R.ROOMNO=G.ROOMNO INNER JOIN HISTORY H ON G.NAME=H.NAME WHERE G.CHECKOUT<'31-JUL-2024';
