CREATE TABLE BOOKS(BOOKID number,TITLE varchar(20),AUTHOR varchar(20),TOTCO NUMBER,AVAILCO NUMBER,primary key(BOOKID));
CREATE TABLE MEMBER(MEMID NUMBER primary key,NAME varchar(20),MEMDATE DATE);
CREATE TABLE BORROW(BORID NUMBER primary key,BOOKID NUMBER,MEMID NUMBER,BORDATE DATE,RETDATE DATE,FINE NUMBER,foreign key(BOOKID) references BOOKS(BOOKID),foreign key(MEMID)references MEMBER(MEMID));
INSERT INTO BOOKS (BOOKID, TITLE, AUTHOR, TOTCO, AVAILCO) 
VALUES (1, 'The Great Gatsby', 'F. Scott Fitzgerald', 100, 5);

INSERT INTO BOOKS (BOOKID, TITLE, AUTHOR, TOTCO, AVAILCO) 
VALUES (2, '1984', 'George Orwell', 150, 150);

INSERT INTO BOOKS (BOOKID, TITLE, AUTHOR, TOTCO, AVAILCO) 
VALUES (3, 'To Kill ', 'Harper Lee', 200, 200);
INSERT INTO MEMBER (MEMID, NAME, MEMDATE) 
VALUES (101, 'Alice Johnson', TO_DATE('2023-01-15', 'YYYY-MM-DD'));

INSERT INTO MEMBER (MEMID, NAME, MEMDATE) 
VALUES (102, 'Bob Smith', TO_DATE('2023-06-20', 'YYYY-MM-DD'));

INSERT INTO MEMBER (MEMID, NAME, MEMDATE) 
VALUES (103, 'Charlie Brown', TO_DATE('2024-02-10', 'YYYY-MM-DD'));
SELECT * FROM BOOKS;
SELECT * FROM MEMBER;

SET SERVEROUTPUT ON;
CREATE OR REPLACE TRIGGER TRIG 
AFTER INSERT ON BORROW
FOR EACH ROW 
DECLARE
 AVAILC NUMBER;
BEGIN
   SELECT AVAILCO INTO AVAILC FROM BOOKS WHERE BOOKID=:NEW.BOOKID;
   IF AVAILC>0 THEN
      update BOOKS SET AVAILCO=AVAILCO-1 WHERE BOOKID=:NEW.BOOKID;
   else 
     DBMS_OUTPUT.PUT_LINE('CANT BORROW');
   END IF;
END TRIG;
/
INSERT INTO BORROW (BORID, BOOKID, MEMID, BORDATE, RETDATE) 
VALUES (1, 1, 101, TO_DATE('2024-03-01', 'YYYY-MM-DD'), TO_DATE('2024-04-15', 'YYYY-MM-DD'));

INSERT INTO BORROW (BORID, BOOKID, MEMID, BORDATE, RETDATE) 
VALUES (2, 2, 102, TO_DATE('2024-04-10', 'YYYY-MM-DD'), TO_DATE('2024-05-20', 'YYYY-MM-DD'));

INSERT INTO BORROW (BORID, BOOKID, MEMID, BORDATE, RETDATE) 
VALUES (3, 3, 103, TO_DATE('2024-05-05', 'YYYY-MM-DD'), TO_DATE('2024-05-15', 'YYYY-MM-DD'));

INSERT INTO BORROW (BORID, BOOKID, MEMID, BORDATE, RETDATE) 
VALUES (4, 3, 103, TO_DATE('2024-07-05', 'YYYY-MM-DD'), TO_DATE('2024-07-15', 'YYYY-MM-DD'));
SELECT * FROM BOOKS;
SELECT * FROM BORROW;

SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE GENFINE(BKID NUMBER,RET DATE,BOR DATE)as
FINEE NUMBER;
DAYY NUMBER;
BEGIN
 DAYY:=RET-BOR-30;
 FINEE:=DAYY*2;
 UPDATE BORROW SET FINE=FINEE WHERE BOOKID=BKID;
END GENFINE;
/

SHOW ERRORS;

DECLARE
 CURSOR CUR IS 
  SELECT BOOKID,RETDATE,BORDATE FROM BORROW WHERE RETDATE>BORDATE+30;
 CUR1 CUR%ROWTYPE;
BEGIN
 OPEN CUR;
  LOOP
   FETCH CUR INTO CUR1;
   EXIT WHEN CUR%NOTFOUND;
   GENFINE(CUR1.BOOKID,CUR1.RETDATE,CUR1.BORDATE);
  END LOOP;
 CLOSE CUR;
END;
/
SELECT * FROM BORROW;
SELECT COUNT(BOOKID),MEMID FROM BORROW group by MEMID;
SELECT * FROM BOOKS WHERE AVAILCO<5;
SELECT * 
FROM (
  SELECT * 
  FROM BORROW 
  ORDER BY FINE DESC
) 
WHERE ROWNUM <= 3;




