-- Create the STUD table
CREATE TABLE RAIL(
    NO INT PRIMARY KEY,
    NAME VARCHAR(20),
    PLACE VARCHAR(20),
    SEATS INT
);
 CREATE SEQUENCE TRAIN
 START WITH 1
 INCREMENT BY 1;
 
 INSERT INTO RAIL(NO,
    NAME,
    PLACE,
    SEATS) VALUES(TRAIN.NEXTVAL,'NETRAVATI','JAIPUR',200);
 INSERT INTO RAIL(NO,
    NAME,
    PLACE,
    SEATS) VALUES(TRAIN.NEXTVAL,'OKHA','DELHI',150);
 INSERT INTO RAIL(NO,
    NAME,
    PLACE,
    SEATS) VALUES(TRAIN.NEXTVAL,'INTER','AGRA',120);

SELECT * FROM RAIL;

CREATE OR REPLACE PROCEDURE RESERVE(SEAT_NEED INT,TNO INT) AS AVAIL_SEAT INT;
BEGIN
 SELECT SEATS INTO AVAIL_SEAT FROM RAIL WHERE NO=TNO;
 IF AVAIL_SEAT>=SEAT_NEED THEN 
  UPDATE RAIL SET SEATS=SEATS-SEAT_NEED WHERE NO=TNO;
  COMMIT;
  DBMS_OUTPUT.PUT_LINE(SEAT_NEED||'RESERVED SUCCESS');
 ELSE 
  DBMS_OUTPUT.PUT_LINE('NO AVAILABLE SEATS');
 END IF;
END RESERVE;
/

CREATE OR REPLACE PROCEDURE CANCEL(SEAT_NEED INT,TNO INT) AS
BEGIN
  UPDATE RAIL SET SEATS=SEATS+SEAT_NEED WHERE NO=TNO;
  COMMIT;
  DBMS_OUTPUT.PUT_LINE(SEAT_NEED||'CANCEL SUCCESS');
END CANCEL;
/

SET SERVEROUTPUT ON;
DECLARE
    TNO INT := &TNO;           -- Prompt for train number
    SEAT_NEED INT := &SEAT_NEED;  -- Prompt for needed seats
    CH INT := &CH;             -- Prompt for choice
BEGIN
    DBMS_OUTPUT.PUT_LINE('1. RESERVE  2. CANCEL');
    IF CH = 1 THEN
        RESERVE(SEAT_NEED, TNO);
    ELSIF CH = 2 THEN
        CANCEL(SEAT_NEED, TNO);
    END IF;
END;
/
SELECT * FROM RAIL;
 
